# Generated by Django 3.1.3 on 2021-05-03 23:43

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(blank=True, max_length=200, null=True)),
                ('Sous_Groupe', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(blank=True, max_length=200, null=True)),
                ('Coef', models.FloatField(blank=True, null=True)),
                ('Total_Heures_Cm', models.FloatField(blank=True, null=True)),
                ('Total_Heures_Td', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(blank=True, max_length=500, null=True)),
                ('Semestre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='L3App.semestre')),
            ],
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(blank=True, max_length=200, null=True)),
                ('Prenom', models.CharField(blank=True, max_length=200, null=True)),
                ('Email', models.EmailField(blank=True, max_length=200, null=True)),
                ('Date_de_naissance', models.DateField(verbose_name='date de naissance')),
                ('Ville', models.CharField(max_length=200, null=True)),
                ('Adresse', models.CharField(blank=True, max_length=200, null=True)),
                ('Nb_Heures_Cm', models.FloatField(blank=True, null=True)),
                ('Nb_Heures_Td', models.FloatField(blank=True, null=True)),
                ('Matieres', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='L3App.matiere')),
            ],
        ),
        migrations.AddField(
            model_name='matiere',
            name='Ue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='L3App.ue'),
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N_Etudiant', models.CharField(blank=True, max_length=200, null=True)),
                ('Ine', models.CharField(blank=True, max_length=200, null=True)),
                ('Nom', models.CharField(blank=True, max_length=200, null=True)),
                ('Prenom', models.CharField(blank=True, max_length=200, null=True)),
                ('Email', models.EmailField(blank=True, max_length=200, null=True)),
                ('Date_de_naissance', models.DateField(verbose_name='date de naissance')),
                ('Pays_de_naissance', models.CharField(blank=True, max_length=200, null=True)),
                ('Ville_de_naissance', models.CharField(blank=True, max_length=200, null=True)),
                ('Adresse', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('cacher', 'cacher'), ('Afficher', 'Afficher')], default='Afficher', max_length=10)),
                ('Groupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='L3App.groupe')),
                ('Tuteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='L3App.professeur')),
            ],
            managers=[
                ('Objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Note', models.FloatField(blank=True, max_length=10, null=True)),
                ('Etudiant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='L3App.etudiant')),
                ('Groupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='L3App.groupe')),
                ('Matiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='L3App.matiere')),
                ('Professeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='L3App.professeur')),
                ('Semestre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='L3App.semestre')),
                ('Ue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='L3App.ue')),
            ],
        ),
    ]
