# Generated by Django 3.1.3 on 2021-05-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L3App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_image'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='status',
            field=models.CharField(choices=[('Afficher', 'Afficher'), ('cacher', 'cacher')], default='Afficher', max_length=10),
        ),
    ]
