# Generated by Django 3.1.3 on 2021-05-04 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('L3App', '0002_auto_20210504_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='Groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupes', to='L3App.groupe'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='status',
            field=models.CharField(choices=[('cacher', 'cacher'), ('Afficher', 'Afficher')], default='Afficher', max_length=10),
        ),
    ]
