# Generated by Django 3.1.3 on 2021-05-04 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('L3App', '0003_auto_20210505_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='Groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Etudiants', to='L3App.groupe'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='status',
            field=models.CharField(choices=[('Afficher', 'Afficher'), ('cacher', 'cacher')], default='Afficher', max_length=10),
        ),
    ]
