# Generated by Django 3.1.3 on 2021-05-06 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('L3App', '0009_auto_20210506_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='Groupe',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='Groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Etudiants', to='L3App.groupe'),
        ),
        migrations.RemoveField(
            model_name='professeur',
            name='Matieres',
        ),
        migrations.AddField(
            model_name='professeur',
            name='Matieres',
            field=models.ManyToManyField(blank=True, null=True, to='L3App.Matiere'),
        ),
    ]
