# Generated by Django 3.1.3 on 2021-05-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L3App', '0010_auto_20210506_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professeur',
            name='Matieres',
            field=models.ManyToManyField(blank=True, null=True, related_name='Prof_list', to='L3App.Matiere'),
        ),
    ]
