# Generated by Django 3.1.3 on 2021-05-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L3App', '0012_auto_20210508_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_image'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='status',
            field=models.CharField(choices=[('Afficher', 'Afficher'), ('cacher', 'cacher')], default='Afficher', max_length=10),
        ),
    ]
