# Generated by Django 3.1.3 on 2021-05-07 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L3App', '0016_auto_20210508_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professeur',
            name='Matieres',
            field=models.ManyToManyField(blank=True, null=True, related_name='Matiere', to='L3App.Matiere'),
        ),
    ]
