# Generated by Django 3.1.3 on 2021-05-08 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L3App', '0018_auto_20210508_0212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='Groupe',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='Groupes',
            field=models.ManyToManyField(blank=True, null=True, related_name='Etudiants', to='L3App.Matiere'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='status',
            field=models.CharField(choices=[('cacher', 'cacher'), ('Afficher', 'Afficher')], default='Afficher', max_length=10),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='Matieres',
            field=models.ManyToManyField(blank=True, null=True, related_name='Professeurs', to='L3App.Matiere'),
        ),
    ]
