# Generated by Django 3.1.3 on 2021-05-08 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L3App', '0020_auto_20210508_0312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='Tuteur',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='Tuteur',
            field=models.ManyToManyField(blank=True, null=True, related_name='Etudiants', to='L3App.Professeur'),
        ),
    ]
