# Generated by Django 3.1.3 on 2021-05-10 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L3App', '0021_auto_20210508_0338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ue',
            old_name='Semestre',
            new_name='Semestres',
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='status',
            field=models.CharField(choices=[('cacher', 'cacher'), ('Afficher', 'Afficher')], default='Afficher', max_length=10),
        ),
    ]
