# Generated by Django 3.1.3 on 2021-05-10 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L3App', '0022_auto_20210510_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='Groupes',
            field=models.ManyToManyField(blank=True, related_name='Etudiants', to='L3App.Groupe'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='Tuteur',
            field=models.ManyToManyField(blank=True, related_name='Etudiants', to='L3App.Professeur'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='status',
            field=models.CharField(choices=[('Afficher', 'Afficher'), ('cacher', 'cacher')], default='Afficher', max_length=10),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='Matieres',
            field=models.ManyToManyField(blank=True, related_name='Professeurs', to='L3App.Matiere'),
        ),
        migrations.RemoveField(
            model_name='ue',
            name='Semestres',
        ),
        migrations.AddField(
            model_name='ue',
            name='Semestres',
            field=models.ManyToManyField(blank=True, related_name='Ues', to='L3App.Semestre'),
        ),
    ]
