# Generated by Django 3.1.3 on 2021-05-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L3App', '0025_auto_20210515_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='Groupes',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='Tuteur',
        ),
        migrations.AddField(
            model_name='groupe',
            name='Etudiants',
            field=models.ManyToManyField(blank=True, related_name='Groupes', to='L3App.Etudiant'),
        ),
        migrations.AddField(
            model_name='professeur',
            name='Etudiants',
            field=models.ManyToManyField(blank=True, related_name='Professeurs', to='L3App.Etudiant'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='status',
            field=models.CharField(choices=[('cacher', 'cacher'), ('Afficher', 'Afficher')], default='Afficher', max_length=10),
        ),
    ]
