# Generated by Django 3.1.3 on 2021-05-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L3App', '0026_auto_20210517_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professeur',
            name='Etudiants',
            field=models.ManyToManyField(blank=True, related_name='Tuteur', to='L3App.Etudiant'),
        ),
    ]
