# Generated by Django 3.1.3 on 2022-08-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L3App', '0027_auto_20210517_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affectation',
            name='Etudiant',
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='L3App/Static/images'),
        ),
    ]
