# Generated by Django 3.1.3 on 2022-08-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L3App', '0028_auto_20220804_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='image',
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='status',
            field=models.CharField(choices=[('Afficher', 'Afficher'), ('cacher', 'cacher')], default='Afficher', max_length=10),
        ),
    ]
